# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f39729379c6416ef3f728d618204fa2588166962f597d270160c9b77026392336876970c2d2afbad8d4f72e106ad64b57936139fbb1b516f0a8dd5f26fac237

test:
  secret_key_base: ffd1e38f08869d11fc910a9ff7bbb22f9dfdc36be62bb3afe58253c06b53ecf84397b15ea2ec975ff8a0320c3568802a7cbbb4de64c04a486fee8dae1bc5812c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
